### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wongster80** [tensquaregames/Vertica-JSON-Extensions#1]
Hi I'm getting the following error running 'make build'.  I am running CentOS 6.5 with gcc 4.4.7

$ make build
mkdir -p `dirname build/Vertica.o`
g++ -I /opt/vertica/sdk/include -std=c++03 -Wall -Wextra -pedantic -fPIC -O3 -c -o build/Vertica.o /opt/vertica/sdk/include/Vertica.cpp
cc1plus: error: unrecognized command line option "-std=c++03"
make: **\* [build/Vertica.o] Error 1

**Comment by panhania** [comment]
According to [this page](https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/Standards.html#Standards) GCC 4.4.7 supports `-std=c++98` and `-std=c++0x` (aliased as `-std=c++11` in newer versions) flags. I have tried with `-std=c++98` both on Clang 3.8 and GCC 6.1.1 and it worked, so it should work on your GCC 4.4.7 too. Simply try changing `-std=c++03` in `CXXFLAGS` variable to `-std=c++98` in the Makefile.

**Comment by wongster80** [comment]
Changing the CXXFLAGS variable works as you suggested.

Thanks!
