### ISSUE TITLE
unsufficient resources error 

### ISSUE THREAD

**Issue by szavgorodni** [tensquaregames/Vertica-JSON-Extensions#2]
The query below returns this error

**_ERROR: Insufficient resources to execute plan on pool sysquery [Request Too Large:File Handles Exceeded: Requested = 21125, Free = 20457 (Limit = 20457, Used = 0)] _**

This query works if I break down nested queries and save intermediate results to separate tables, but of course, it takes additional time to save intermediate results to the disk.

Even then the requested file handles are abnormally big - around 8,000

The issue seems to be related to JsonQuery consuming excessive number of  File Handles
Parsing maps with big number of keys can consume too many File Handles and eventually lead to the error above 

Is this a known issue ?

`SELECT 
    key1,
    key2,
    key3,
    key4,
    JsonArrayUnnest(key3) OVER (PARTITION BY key1, key2, key3, key4, key31, key32, key33, key34, key35, key36) AS value_l2 
FROM (  
    SELECT
            JsonQuery(content, 'key1')                      AS key1 ,
            JsonQuery(content, 'key2')                      AS key2 ,
            JsonQuery(content, 'key3')                      AS key3,
            JsonQuery(content, 'key4')                      AS key4,

```
        JsonQuery(JsonQuery(content, 'key3'), 'key31')  AS key31,
        JsonQuery(JsonQuery(content, 'key3'), 'key32')  AS key32,
        JsonQuery(JsonQuery(content, 'key3'), 'key33')  AS key33,
        JsonQuery(JsonQuery(content, 'key3'), 'key34')  AS key34,
        JsonQuery(JsonQuery(content, 'key3'), 'key35')  AS key35,

        JsonQuery(JsonQuery(content, 'key3'), 'key36')  AS key36
    FROM (  
```

select 
JsonArrayUnnest('[{"key1":"key1_value","key2":"key2_value","key3":"key3_value","key4":"key4_value"}]') OVER () AS content 

```
        ) j1 
```

) j2

**Comment by panhania** [comment]
Thanks for reporting.

Turns out Vertica allocates 100 file handles per call by default. Since our extension does not use these at all, we can safely constrain this number to 0. It should work fine now (and of course feel free to reopen if it does not!).
