### ISSUE TITLE
JsonArrayUnnest - Only supports varchar limiting to 65000 character

### ISSUE THREAD

**Issue by wongster80** [tensquaregames/Vertica-JSON-Extensions#3]
Hi ,

JsonArrayUnnest only supports data type varchar limiting the size to 65000.  We have a need for it to be of long type.  Would it be possible?

Thank you

**Comment by jdziemidowicz** [comment]
Seems it should be possible by modifying AbstractJsonArrayUnnestFactory in JsonUnnest.cpp and adding call to addLongVarchar(). Try if it works and feel free to submit a pull request :)

https://my.vertica.com/docs/8.0.x/HTML/Content/CppSDK/class_vertica_1_1_transform_function_factory.htm
https://my.vertica.com/docs/8.0.x/HTML/Content/CppSDK/class_vertica_1_1_column_types.htm

**Comment by wongster80** [comment]
Hello,

It works only when I only addLongVarchar() but have to remove addVarchar() in the class, or else i get:
>[Error] Script lines: 2-22 -------------------------
 [Vertica][VJDBC](3457) ERROR: Function public.JsonQuery(long varchar, varchar) does not exist, or permission is denied for public.JsonQuery(long varchar, varchar)

Here's the modified AbstractJsonArrayUnnestFactory class
https://gist.github.com/wongster80/77ccee824bef558d31f6678f6a0b5107

Is there any ways to make the class accept either long varchar or varchar ?

Thank you

**Comment by jdziemidowicz** [comment]
Vertica documentation states that there is an implicit type coercion from VARCHAR to LONG VARCHAR. Doesn't that work for you?

**Comment by jdziemidowicz** [comment]
That should be fixed by #4
